name: dev-container
services:
  base:
    container_name: dev-base
    build: 
      dockerfile: Dockerfile.base
    command: sleep infinity
    init: true
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ${HOME}/.ssh
        target: /root/.ssh

